### ISSUE TITLE
Adjusting length of data in non-iid non-binary case

### ISSUE THREAD

**Issue by olivier-perso** [usnistgov/SP800-90B_EntropyAssessment#127] opened 2019-08-21 17:48 UTC
In the file `./cpp/non_iid_main.cpp`, line 139 ensures that the length of the binary string doesn't go beyond 1,000,000 symbols if flag `-t` is enabled, i.e.:

```
if(!all_bits && (data.blen > MIN_SIZE)) data.blen = MIN_SIZE;
```

However, there doesn't seem to be any line that provides a similar option in the non-binary case. To verify this, I ran the non-IID track twice on the same dataset of 8-bit words: once using the `-t` flag and once using the `-a` flag. As expected, I got the exact same results both time. What I suggest is to add a single line of code as follows:

```
if(!all_bits && (data.len > MIN_SIZE)) data.len = MIN_SIZE;
```

**Comment by joshuaehill** [comment] 2019-08-21 18:08
I may well have missed something, but if you want to restrict the amount of data that the tool runs on, why not just truncate the file prior to providing it to the tool?

The reason that the ``-t`` option exists is that 90B explicitly allows truncation of the _translated_ binary form of the input data set (see SP800-90B Section 3.1.3). Note, this flag does not change anything in the instance where the underlying data set is already binary data, it only affects the production of H_bitstring, and H_bitstring is never calculated in the instance where the underlying data is already bit-oriented.

I suspect the notion was that it may be impractical to test up to 8*data.len binary samples in some instances where testing data.len samples may still work out.

At this point (given the current state of the testing tool), such instances should be rare, and I would generally suggest not using the "-t" option. For most sources, avoiding truncation will provide a more meaningful result (which is often higher than the value produced when the binary data is truncated!)

**Comment by olivier-perso** [comment] 2019-08-21 18:38
Hi,

I definitely agree with you that using the "-a" option is best in most
cases because more data provides a more meaningful result. However, I got
curious when I noticed that the results were precisely the same when using
the "-a" flag and the "-t" flag. I still think it would be useful to
provide the option since using smaller files reduce the computation time
and still provides fairly good results (and setting a flag is more
straightforward than changing a file's size). In fact, I thought that the
"-t" flag's only purpose was to quickly provide a (rougher) min-entropy
estimate.

Regards,

Olivier

Le mer. 21 août 2019 à 14:08, Joshua E. Hill <notifications@github.com> a
écrit :

**Comment by joshuaehill** [comment] 2019-08-21 18:49
That is not the purpose of the ``-t`` flag.

The tool already have the ability to truncate to a user-supplied amount of data using the ``-l`` flag (e.g., ``-l 0,1000000`` to take the first 1000000 samples). Does this accomplish what you were looking for?

**Comment by olivier-perso** [comment] 2019-08-21 18:56
Yes, I'll use the -l flag from now on.

Le mer. 21 août 2019 à 14:49, Joshua E. Hill <notifications@github.com> a
écrit :

**Comment by joshuaehill** [comment] 2019-08-21 18:57
If the issue is resolved, could you please close the issue? Thanks!

**Closed** 2019-08-21 19:02 UTC
