### ISSUE TITLE
Makefile seems very specific to the particular devolopment system used

### ISSUE THREAD

**Issue by joshuaehill** [usnistgov/SP800-90B_EntropyAssessment#68] opened 2018-09-22 19:34 UTC
In particular, the various include directories in "INC" shouldn't be necessary (and indeed, cause problems on systems where the defaults are not those that are specified).

**Comment by celic** [comment] 2018-09-24 19:37
Duplicate of #64? Perhaps that one can be closed in favor of this one.

**Comment by joshuaehill** [comment] 2018-09-24 20:17
It's related, in that they are both Makefile issues. This one is mainly about the directories listed in the "INC" Makefile variable, which aren't appropriate for many (most?) other systems.

**Closed** 2019-01-31 21:57 UTC
