### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by mbleasel** [usnistgov/SP800-90B_EntropyAssessment#205] opened 2022-12-23 10:12 UTC
![Screenshot from 2022-12-23 20-27-14](https://user-images.githubusercontent.com/21963283/209315201-0d76a1bb-a5a3-4b01-9ab2-efbd588270cb.png)
Hi, there appears to be an error in the TestRunUtils.h Lines 107, 110 and 120 where fileLen was not declared.   Instead of declaring fileLen I changed fileLen to fileLength which was declared.  While the program appeared to then compile correctly - no further testing was performed.  I do not have enough experience to know if this is correct.

**Comment by joshuaehill** [comment] 2022-12-23 17:20
This is a duplicate of Issue #202, and is resolved in PR #204.

**Comment by burtw** [comment] 2023-01-07 23:01
I am getting ready to submit an 800-90B report to NIST for a client.  I have been using a very old version of this code to do all my data analysis so I decided to rerun all my data using the "latest and greatest".  I am using Ubuntu 22.04 and cloned the repository.  When I did this I got this bug.  I seem to have two choices:  Use the PR or use the 1.1.5 release.  The 1.1.5 release gives me all the warnings about the deprecated interface, and the PR is not an official release.  

Question is:  how long will it be until the next official release (1.1.6 I assume) that fixes the use of the deprecated interface and fixes this build issue?

I would prefer to run my data on that next release if possible.  If it is going to take a long time I will just run it on the current 1.1.5 release that uses the deprecated interface.

**Comment by mbleasel** [comment] 2023-01-08 01:31
Hi, If you are referring to the compiling issue and the variable filelen,
then Josh appears to have fixed the issue in TestRunUtils.h:
https://github.com/joshuaehill/SP800-90B_EntropyAssessment/blob/ShaFix/cpp/shared/TestRunUtils.h
Josh made a few changes to this file.  After replacing TestRunUtils.h with
Josh's the program compiles.  I have also run a couple of binary files with
ea_iid and ea_non_iid.  Outputs 'appear' as expected.  However, I have only
just started to use this software.  Hope this helps.

**Comment by joshuaehill** [comment] 2023-01-08 17:33
I believe that NIST has previously suggested that testing be done using tagged releases (in this case v1.1.5). NIST is clearly not running the current master branch in their testing, as the current master branch doesn't compile.

You would seem to have a few options:
1. You could use PR #204 (which I would guess will eventually be integrated into the master branch and eventually tagged for some future release) applied against the master branch.
2. You could link the tool to a version of OpenSSL that doesn't issue such complaints and use the v1.1.5 release.
3. You could filter out the library complaints and use the v1.1.5.

**Comment by burtw** [comment] 2023-01-09 16:56
Yes, I plan to use 1.1.5 unless 1.1.6 is going to be released soon.  When will 1.1.6 be released (with the SHA256 changes plus the fixes for what was broken by the SHA 256 changes plus all other pending changes and pull requests)?

**Closed** 2023-01-10 17:03 UTC
